name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Runs a oneline script
        run: echo Hello World
      - name: Runs a multiline script
        run: |
          echo Hello again
          echo and again
